server:
  port: 49032
spring:
  datasource:
    url: jdbc:mysql://101.43.145.108:3306/getoffreminder?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: getoffreminfinal
    password: l198923.
  redis:
    database: 0
    host: 101.43.145.108
    port: 6370
    password: l198923.
    timeout: 1000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
mybatis:
  type-aliases-package: com.liu.getOffBusReminder.dao.entity
  mapper-locations: classpath:mapper/*.xml
